# Set theme for page; see https://pages.github.com/themes/ for list of supported themes
theme: jekyll-theme-slate #minima

# Title and description of page
title: Proton Irradiation at Bonn University
description: Thomas, you should update this

# Logo to be displayed on main page
logo: /figs/silab_logo.png

# Better markdown app
markdown: kramdown
