# Set theme for page; see https://pages.github.com/themes/ for list of supported themes
theme: jekyll-theme-slate #minima

# Title and description of page
title: Proton Irradiation Site for Silicon Detectors at Bonn University
 
#/figs/silab_logo.png
# Logo to be displayed on main page

logo: figs/Logo_Silab_PI_HISKP_UniBonn.PNG
#logo1: /figs/ubonn_logo.jpg 
#logo2: /figs/pi_logo.png
#logo3: /figs/hiskp_logo.png
#logo: /figs/silab_logo.png

# Better markdown app
markdown: kramdown
